name: mobile
description: "Nabd Thermocare Flutter App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.9

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  #  ASSETS (for social icons)
  assets:
    - assets/icons/
    - assets/fonts/

  #  FONTS (Alexandria)
  fonts:
    - family: Alexandria
      fonts:
        - asset: assets/fonts/Alexandria-Regular.ttf
        - asset: assets/fonts/Alexandria-Medium.ttf
          weight: 500
        - asset: assets/fonts/Alexandria-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Alexandria-Bold.ttf
          weight: 700