import 'dart:async';
import 'dart:math';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';

class VirtualIotReadingSnapshot {
  final int heartRate;
  final int oxygen;
  final double temperature;
  final int systolic;
  final int diastolic;
  final DateTime recordedAt;

  const VirtualIotReadingSnapshot({
    required this.heartRate,
    required this.oxygen,
    required this.temperature,
    required this.systolic,
    required this.diastolic,
    required this.recordedAt,
  });

  String get bloodPressureText => '$systolic/$diastolic mmHg';
}

class VirtualIotReadingService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;
  final Random _random = Random();

  Timer? _timer;

  final StreamController<VirtualIotReadingSnapshot> _controller =
      StreamController<VirtualIotReadingSnapshot>.broadcast();

  Stream<VirtualIotReadingSnapshot> get readingsStream => _controller.stream;

  bool get isRunning => _timer != null;

  Future<void> start() async {
    if (_timer != null) return;

    await _generateAndSaveReading();

    _timer = Timer.periodic(const Duration(seconds: 5), (_) async {
      try {
        await _generateAndSaveReading();
      } catch (_) {
        // Keep demo running even if one Firebase write fails.
      }
    });
  }

  Future<void> stop() async {
    _timer?.cancel();
    _timer = null;
  }

  Future<void> _generateAndSaveReading() async {
    final user = _auth.currentUser;

    if (user == null) {
      throw Exception('You must be logged in to save virtual readings.');
    }

    final now = DateTime.now();

    final reading = VirtualIotReadingSnapshot(
      heartRate: 68 + _random.nextInt(28), // 68 - 95 bpm
      oxygen: 94 + _random.nextInt(7), // 94 - 100%
      temperature: double.parse(
        (36.4 + (_random.nextDouble() * 1.0)).toStringAsFixed(1),
      ), // 36.4 - 37.4 °C
      systolic: 112 + _random.nextInt(24), // 112 - 135
      diastolic: 72 + _random.nextInt(16), // 72 - 87
      recordedAt: now,
    );

    final userRef = _firestore.collection('users').doc(user.uid);
    final batch = _firestore.batch();

    void addVital({
      required String type,
      required double? value,
      required double? systolic,
      required double? diastolic,
      required String unit,
    }) {
      final data = {
        'type': type,
        'value': value,
        'systolic': systolic,
        'diastolic': diastolic,
        'unit': unit,
        'recordedAt': Timestamp.fromDate(now),
        'notes': 'Generated by virtual IoT demo',
        'source': 'wearable',
        'isVirtual': true,
        'createdAt': FieldValue.serverTimestamp(),
      };

      batch.set(userRef.collection('vitals').doc(), data);
      batch.set(userRef.collection('iotReadings').doc(), data);
    }

    addVital(
      type: 'heartRate',
      value: reading.heartRate.toDouble(),
      systolic: null,
      diastolic: null,
      unit: 'bpm',
    );

    addVital(
      type: 'oxygen',
      value: reading.oxygen.toDouble(),
      systolic: null,
      diastolic: null,
      unit: '%',
    );

    addVital(
      type: 'temperature',
      value: reading.temperature,
      systolic: null,
      diastolic: null,
      unit: '°C',
    );

    addVital(
      type: 'bloodPressure',
      value: null,
      systolic: reading.systolic.toDouble(),
      diastolic: reading.diastolic.toDouble(),
      unit: 'mmHg',
    );

    await batch.commit();

    _controller.add(reading);
  }

  void dispose() {
    _timer?.cancel();
    _controller.close();
  }
}