import 'dart:async';
import 'dart:math';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';

class VirtualIotReadingSnapshot {
  final int heartRate;
  final int oxygen;
  final double temperature;
  final int systolic;
  final int diastolic;
  final DateTime recordedAt;
  final bool isCritical;
  final String? criticalReason;

  const VirtualIotReadingSnapshot({
    required this.heartRate,
    required this.oxygen,
    required this.temperature,
    required this.systolic,
    required this.diastolic,
    required this.recordedAt,
    this.isCritical = false,
    this.criticalReason,
  });

  String get bloodPressureText => '$systolic/$diastolic mmHg';
}

class VirtualIotReadingService {
  VirtualIotReadingService._internal();

  static final VirtualIotReadingService instance =
      VirtualIotReadingService._internal();

  factory VirtualIotReadingService() => instance;

  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;
  final Random _random = Random();

  Timer? _timer;

  bool _criticalDemoMode = false;
  bool _sosAlreadyTriggeredForCurrentDemo = false;

  DateTime? _lastSosTriggeredAt;
  VirtualIotReadingSnapshot? _lastReading;

  final StreamController<VirtualIotReadingSnapshot> _controller =
      StreamController<VirtualIotReadingSnapshot>.broadcast();

  Stream<VirtualIotReadingSnapshot> get readingsStream => _controller.stream;

  bool get isRunning => _timer != null;
  bool get isCriticalDemoRunning => _criticalDemoMode;
  VirtualIotReadingSnapshot? get lastReading => _lastReading;

  Future<void> start({bool criticalDemo = false}) async {
    if (_timer != null) return;

    _criticalDemoMode = criticalDemo;
    _sosAlreadyTriggeredForCurrentDemo = false;

    await _generateAndSaveReading();

    _timer = Timer.periodic(const Duration(seconds: 5), (_) async {
      try {
        await _generateAndSaveReading();
      } catch (_) {
        // Keep demo running even if one Firebase write fails.
      }
    });
  }

  Future<void> startCriticalDemo() async {
    await stop();
    await start(criticalDemo: true);
  }

  Future<void> stop() async {
    _timer?.cancel();
    _timer = null;
    _criticalDemoMode = false;
    _sosAlreadyTriggeredForCurrentDemo = false;
  }

  Future<void> _generateAndSaveReading() async {
    final user = _auth.currentUser;

    if (user == null) {
      throw Exception('You must be logged in to save virtual readings.');
    }

    final now = DateTime.now();

    final reading = _criticalDemoMode
        ? _generateCriticalReading(now)
        : _generateNormalReading(now);

    _lastReading = reading;

    final userRef = _firestore.collection('users').doc(user.uid);
    final batch = _firestore.batch();

    void addVital({
      required String type,
      required double? value,
      required double? systolic,
      required double? diastolic,
      required String unit,
    }) {
      final data = {
        'type': type,
        'value': value,
        'systolic': systolic,
        'diastolic': diastolic,
        'unit': unit,
        'recordedAt': Timestamp.fromDate(now),
        'notes': reading.isCritical
            ? 'Critical virtual IoT demo reading'
            : 'Generated by virtual IoT demo',
        'source': 'wearable',
        'isVirtual': true,
        'isCritical': reading.isCritical,
        'criticalReason': reading.criticalReason,
        'createdAt': FieldValue.serverTimestamp(),
      };

      batch.set(userRef.collection('vitals').doc(), data);
      batch.set(userRef.collection('iotReadings').doc(), data);
    }

    addVital(
      type: 'heartRate',
      value: reading.heartRate.toDouble(),
      systolic: null,
      diastolic: null,
      unit: 'bpm',
    );

    addVital(
      type: 'oxygen',
      value: reading.oxygen.toDouble(),
      systolic: null,
      diastolic: null,
      unit: '%',
    );

    addVital(
      type: 'temperature',
      value: reading.temperature,
      systolic: null,
      diastolic: null,
      unit: '°C',
    );

    addVital(
      type: 'bloodPressure',
      value: null,
      systolic: reading.systolic.toDouble(),
      diastolic: reading.diastolic.toDouble(),
      unit: 'mmHg',
    );

    await batch.commit();

    _controller.add(reading);

    if (reading.isCritical) {
      await _triggerSosIfAllowed(reading);
    }
  }

  VirtualIotReadingSnapshot _generateNormalReading(DateTime now) {
    return VirtualIotReadingSnapshot(
      heartRate: 68 + _random.nextInt(28),
      oxygen: 94 + _random.nextInt(7),
      temperature: double.parse(
        (36.4 + (_random.nextDouble() * 1.0)).toStringAsFixed(1),
      ),
      systolic: 112 + _random.nextInt(24),
      diastolic: 72 + _random.nextInt(16),
      recordedAt: now,
      isCritical: false,
    );
  }

  VirtualIotReadingSnapshot _generateCriticalReading(DateTime now) {
    return VirtualIotReadingSnapshot(
      heartRate: 138,
      oxygen: 86,
      temperature: 39.4,
      systolic: 184,
      diastolic: 122,
      recordedAt: now,
      isCritical: true,
      criticalReason:
          'Critical demo: oxygen is low, blood pressure is dangerously high, heart rate is high, and temperature is high.',
    );
  }

  Future<void> _triggerSosIfAllowed(VirtualIotReadingSnapshot reading) async {
    final user = _auth.currentUser;
    if (user == null) return;

    if (_sosAlreadyTriggeredForCurrentDemo) return;

    final now = DateTime.now();

    if (_lastSosTriggeredAt != null &&
        now.difference(_lastSosTriggeredAt!).inSeconds < 60) {
      return;
    }

    _sosAlreadyTriggeredForCurrentDemo = true;
    _lastSosTriggeredAt = now;

    final sosData = {
      'status': 'triggered',
      'triggeredBy': 'autoCriticalVitalsDemo',
      'reason': reading.criticalReason,
      'messageSent': false,
      'address': 'Demo location - Tripoli, Lebanon',
      'latitude': null,
      'longitude': null,
      'createdAt': FieldValue.serverTimestamp(),
      'recordedAt': Timestamp.fromDate(now),
      'vitals': {
        'heartRate': reading.heartRate,
        'oxygen': reading.oxygen,
        'temperature': reading.temperature,
        'systolic': reading.systolic,
        'diastolic': reading.diastolic,
      },
      'message':
          'Automatic SOS triggered because virtual demo vitals reached critical values.',
    };

    await _firestore
        .collection('users')
        .doc(user.uid)
        .collection('sosLogs')
        .add(sosData);
  }

  // Important:
  // Do NOT stop the timer here.
  // Screens call dispose() when you leave the page.
  // The demo must keep running so Home can keep updating.
  void dispose() {}
}