// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLJpLmBCaRx_HxS1Z8ADMcaUGzlPkPCHA',
    appId: '1:328220398396:web:bb61b1029aa228dc6cc439',
    messagingSenderId: '328220398396',
    projectId: 'nabad1',
    authDomain: 'nabad1.firebaseapp.com',
    storageBucket: 'nabad1.firebasestorage.app',
    measurementId: 'G-1LCWEFM5NM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBusaOPQsignOhW-qR2flvjGky2A_1uSjc',
    appId: '1:328220398396:android:894895a8c44572c96cc439',
    messagingSenderId: '328220398396',
    projectId: 'nabad1',
    storageBucket: 'nabad1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXCiKCgbAEJbVg4Tc-DoNL8m-wRlL4iaI',
    appId: '1:328220398396:ios:f5e1386c760eecfa6cc439',
    messagingSenderId: '328220398396',
    projectId: 'nabad1',
    storageBucket: 'nabad1.firebasestorage.app',
    iosClientId: '328220398396-dv246v8o3hhrq4u704nqkeq1p1pi551a.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXCiKCgbAEJbVg4Tc-DoNL8m-wRlL4iaI',
    appId: '1:328220398396:ios:f5e1386c760eecfa6cc439',
    messagingSenderId: '328220398396',
    projectId: 'nabad1',
    storageBucket: 'nabad1.firebasestorage.app',
    iosClientId: '328220398396-dv246v8o3hhrq4u704nqkeq1p1pi551a.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLJpLmBCaRx_HxS1Z8ADMcaUGzlPkPCHA',
    appId: '1:328220398396:web:2accf30b581cbaca6cc439',
    messagingSenderId: '328220398396',
    projectId: 'nabad1',
    authDomain: 'nabad1.firebaseapp.com',
    storageBucket: 'nabad1.firebasestorage.app',
    measurementId: 'G-EH251975FT',
  );
}
